---
name: Feature
description: Add a new Feature issue
title: "[feat]: "
labels: ["dev"]
type: "Feature"
body:
  - type: textarea
    attributes:
      label: Updated Feature or Behavior
      description: A concise description of what you would like to see or have happen.
      placeholder: ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the defect you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
