---
name: Risk
description: Add a new Risk issue
title: "[risk]: "
labels: ["dev"]
type: "Risk"
body:
  - type: textarea
    attributes:
      label: Current Risk
      description: A concise description of what you are seeing or experiencing.
      placeholder: ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits
      description: A concise description of how this will alleviate some risk.
      placeholder: ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the risky behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the defect you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
