name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ORG_PROJECT_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to main SF (rrGlobal) Project Board
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/rrglobal/projects/3'
